const dataSet = {
  Today: [
    { name: "12 AM", value: 0 },
    { name: "1 AM", value: 0 },
    { name: "2 AM", value: 0 },
    { name: "3 AM", value: 0 },
    { name: "4 AM", value: 0 },
    { name: "5 AM", value: 0 },
    { name: "6 AM", value: 0 },
    { name: "7 AM", value: 0 },
    { name: "8 AM", value: 0 },
    { name: "9 AM", value: 0 },
    { name: "10 AM", value: 0 },
    { name: "11 AM", value: 0 },
    { name: "12 PM", value: 0 },
    { name: "1 PM", value: 0 },
    { name: "2 PM", value: 0 },
    { name: "3 PM", value: 0 },
    { name: "4 PM", value: 0 },
    { name: "5 PM", value: 0 },
    { name: "6 PM", value: 0 },
    { name: "7 PM", value: 0 },
    { name: "8 PM", value: 0 },
    { name: "9 PM", value: 0 },
    { name: "10 PM", value: 0 },
    { name: "11 PM", value: 0 }
  ],
  Yesterday: [
    { name: "12 AM", value: 5 },
    { name: "1 AM", value: 10 },
    { name: "2 AM", value: 7 },
    { name: "3 AM", value: 8 },
    { name: "4 AM", value: 12 },
    { name: "5 AM", value: 14 },
    { name: "6 AM", value: 6 },
    { name: "7 AM", value: 9 },
    { name: "8 AM", value: 13 },
    { name: "9 AM", value: 17 },
    { name: "10 AM", value: 15 },
    { name: "11 AM", value: 11 },
    { name: "12 PM", value: 16 },
    { name: "1 PM", value: 14 },
    { name: "2 PM", value: 12 },
    { name: "3 PM", value: 10 },
    { name: "4 PM", value: 13 },
    { name: "5 PM", value: 15 },
    { name: "6 PM", value: 9 },
    { name: "7 PM", value: 7 },
    { name: "8 PM", value: 8 },
    { name: "9 PM", value: 6 },
    { name: "10 PM", value: 5 },
    { name: "11 PM", value: 3 }
  ],
  Last_7_days: [
    { name: "Day 1", value: 10 },
    { name: "Day 2", value: 20 },
    { name: "Day 3", value: 15 },
    { name: "Day 4", value: 25 },
    { name: "Day 5", value: 30 },
    { name: "Day 6", value: 35 },
    { name: "Day 7", value: 40 }
  ],
  Last_14_days: [
    { name: "Day 1", value: 10 },
    { name: "Day 2", value: 20 },
    { name: "Day 3", value: 15 },
    { name: "Day 4", value: 25 },
    { name: "Day 5", value: 30 },
    { name: "Day 6", value: 35 },
    { name: "Day 7", value: 40 },
    { name: "Day 8", value: 45 },
    { name: "Day 9", value: 50 },
    { name: "Day 10", value: 55 },
    { name: "Day 11", value: 60 },
    { name: "Day 12", value: 65 },
    { name: "Day 13", value: 70 },
    { name: "Day 14", value: 75 }
  ],
  Last_30_days: [
    { name: "Day 1", value: 10 },
    { name: "Day 2", value: 20 },
    { name: "Day 3", value: 15 },
    { name: "Day 4", value: 25 },
    { name: "Day 5", value: 30 },
    { name: "Day 6", value: 35 },
    { name: "Day 7", value: 40 },
    { name: "Day 8", value: 45 },
    { name: "Day 9", value: 50 },
    { name: "Day 10", value: 55 },
    { name: "Day 11", value: 60 },
    { name: "Day 12", value: 65 },
    { name: "Day 13", value: 70 },
    { name: "Day 14", value: 75 },
    { name: "Day 15", value: 80 },
    { name: "Day 16", value: 85 },
    { name: "Day 17", value: 90 },
    { name: "Day 18", value: 95 },
    { name: "Day 19", value: 100 },
    { name: "Day 20", value: 105 },
    { name: "Day 21", value: 110 },
    { name: "Day 22", value: 115 },
    { name: "Day 23", value: 120 },
    { name: "Day 24", value: 125 },
    { name: "Day 25", value: 130 },
    { name: "Day 26", value: 135 },
    { name: "Day 27", value: 140 },
    { name: "Day 28", value: 145 },
    { name: "Day 29", value: 150 },
    { name: "Day 30", value: 155 }
  ],
  Last_90_days: [
    // Populate similar to above
  ]
};

export default dataSet;
